-- AlterEnum
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'GRADUATED_CURVE_CONFIGURED';

-- AlterTable
ALTER TABLE "CreatorProfile" ADD COLUMN IF NOT EXISTS "curve_milestones" JSONB,
ADD COLUMN IF NOT EXISTS "base_exponent" INTEGER NOT NULL DEFAULT 1;
